osx_image: xcode8
language: objective-c
xcode_project: BricBrac.xcodeproj
xcode_scheme: BricBrac
script:
  - xcodebuild test -project BricBrac.xcodeproj -sdk macosx -scheme BricBrac GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  - xcodebuild test -project BricBrac.xcodeproj -sdk iphonesimulator -scheme BricBrac GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  - xcodebuild test -project BricBrac.xcodeproj -sdk macosx -scheme Curio

after_success:
  - bash <(curl -s https://codecov.io/bash)

